### PR TITLE
chore: update to llama cpp python server  0.2.90

### PR DESCRIPTION
**Pull request by jeffmaury**
### What does this PR do?

Switch llama-cpp-python to 0.2.90 and update Vulkan as compilation changed

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

N/A

### How to test this PR?

N/A

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
is the jeffmaury repository expected in the final PR ?

**Comment by jeffmaury** [comment]
> is the jeffmaury repository expected in the final PR ?

For the time being, yes. The newest llama-cpp-python requires for Vulkan compilation a new package that is not in EPEL9. So I mimic what Sergio did for libkrun and created those packages in Fedora COPR. Will check if we can add them in EPEL9

**Comment by benoitf** [comment]
I was just wondering if it could not be part of the Dockerfile ? so it's maintained in the Dockerfile

**Comment by benoitf** [comment]
ok need to wait the end of the year then
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/#get-started-using-arm-hosted-runners-today

there will be arm64 linux runners

**Review by benoitf — APPROVED** [review]

**Pull request merged**
